name: Tests

on:
- pull_request
- push

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [10, 12, 14]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Install node_modules
      run: yarn

    - name: Run tests
      run: yarn test
